### ISSUE TITLE
Basic information not working when we access with a wrong token

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#1]
**Explanation:** We have two ways of access the software, without token and with token. The token is a tokenized client id, that allows us to know who is the client in the main software. When we don't have it, it is a new client.

http://smartapp.axiomdev.ca/
and
http://smartapp.axiomdev.ca/?token=88yc0siR3-2CEI364e7E7GqOv1-KnVyV

**Error:** If you try to access with a wrong token, it shows nothing.
**Expected result:** show a page saying that the token is invalid.

**Comment by rwwagner90** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/sX3VCj0f/1-test)

**Comment by axiommike** [comment]
Robert if you want to add me to your Trello board you can mike@axiommortgage.ca.  If it doesn't make sense to do so that is fine too

**Comment by RobbieTheWagner** [comment]
@axiommike I will add you. I am mainly just pulling each issue into Trello for time tracking. I use Paydirt to track time on Trello cards.
