### ISSUE TITLE
Fix format-number error

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#14]
Fill all fields on Basic information page.

It will redirect you to the Applicants page. On console, you may see the following error.
![captura de tela 2016-12-15 as 17 33 15](https://cloud.githubusercontent.com/assets/1010637/21239117/b2db5944-c2ec-11e6-96b8-f7a26f7b5055.png)

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix format-number error](https://trello.com/c/Q3FvLK1f/10-fix-format-number-error)
