### ISSUE TITLE
Another format-number error

### ISSUE THREAD

**Issue by RobbieTheWagner** [axiommike/smart-app#19]
In the adding assets part of the second page, the format-number helper is passed `assetProxy.value`, but I do not think `assetProxy` actually refers to anything. I could not find it in the JS anywhere. The asset model also appears blank. Are assets working? Need to iron some of this out.

**Comment by ericmaicon** [comment]
@rwwagner90 , this may be a problem that I left when I refactor to the new version.
You may see in the following code what you are asking for:

https://github.com/axiommike/smart-app/blob/v1.0/app/components/asset-instance.js#L10
https://github.com/axiommike/smart-app/blob/v1.0/app/controllers/mortgage-application/assets.js

My idea was to remove the assetProxy and use only asset (as model), to hit directly in the same page with the API (after click in next step).

**Comment by RobbieTheWagner** [comment]
@ericmaicon ah, I see. I think using the `asset` model directly sounds fine, I just need to change all `assetProxy` references.

Do you know if we need that `autosave` that was in there for anything?

**Comment by ericmaicon** [comment]
Since my plan was to hit the api every time that we click on "next", I don't see a point on autosave. Do you? 

Let me know your thoughts.

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Another format-number error](https://trello.com/c/R0j9DYr3/13-another-format-number-error)

**Comment by axiommike** [comment]
I like the idea of autosaving.  At least then we get customer info even if they do not 'submit'
