### ISSUE TITLE
breadcrumb appears in Basic information page

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#2]
**Explanation:** In the very first page, you should see a breadcrumb in the header page.
http://smartapp.axiomdev.ca/
**Error:** The breadcrumb is showing.
**Expected result:** Hide the breadcrumb, since it is the first step and we don't know where the user goes from there (we have two actions: contact and next step. It should appear just in the next step).

**Comment by srsgores** [comment]
Has this requirement been tested to improve usability?  [According to Neilsen's usability heurstic 1, users should **always be aware of the current state in navigation**](https://www.nngroup.com/articles/ten-usability-heuristics/).

**Comment by ericmaicon** [comment]
Thanks @srsgores , we can have the breadcrumb here, but with next links disabled.

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [breadcrumb appears in Basic information page](https://trello.com/c/j58x5Zao/2-breadcrumb-appears-in-basic-information-page)

**Comment by srsgores** [comment]
@ericmaicon, though I no longer maintain this project, I will chime in on *why* this was the case:

When we performed usability testing with our in-house agents, we noticed that some of the agents needed to input data like client addresses to kick-start an application.  In these cases, they needed to **skip** to the contact details found in step 2.  The user story looked something like this:

> As a mortgage broker specializing in residential mortgage loans, I want to provide my prospective client with a pre-filled mortgage application with my client's address and postal code so that I can encourage him/her to complete the process and eventually get him/her approved for a mortgage loan.

**Comment by axiommike** [comment]
Thanks for the feedback Sean I appreciate it.  Though the quote you reference is not about skipping forward it is about pre-populating the application with data that we may already have in our backend database.
