### ISSUE TITLE
Show the right name in the thank you page

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#3]
Explanation: In the very first page, fill every field and click on "Contact me now". It will redirect you to the "thank-you" route.
http://smartapp.axiomdev.ca/
Error: The breadcrumb should show that you are in the last page. It should show the applicant.first_name after the word `Thanks, `.

**Comment by srsgores** [comment]
Potential issue with [``model.dear``](https://github.com/axiommike/smart-app/blob/master/app/templates/thank-you.hbs#L5) in the returned ``model`` json from server?

**Comment by ericmaicon** [comment]
Thanks @srsgores. So, to work with the new api, I might changed the logic. When it come from `index`route, it uses an applicant model, which has `first_name` attribute. When it comes from `liabilities` route, it has a mortgage model, which has the `dear` attribute. I did an if indeed, not sure why it didn't work.

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show the right name in the thank you page](https://trello.com/c/P9AqgnAE/3-show-the-right-name-in-the-thank-you-page)

**Comment by RobbieTheWagner** [comment]
@ericmaicon the API still seems to be broken here. A POST to the server of a new applicant returns 200:

<img width="372" alt="screen shot 2016-12-17 at 4 30 19 pm" src="https://cloud.githubusercontent.com/assets/2640861/21289886/62d99bb4-c476-11e6-9f1b-a8084c17a645.png">

And it POSTs this data:

<img width="821" alt="screen shot 2016-12-17 at 4 30 28 pm" src="https://cloud.githubusercontent.com/assets/2640861/21289887/6ec8a370-c476-11e6-8292-41e0ef10810f.png">

The response from the API is a record with just the `id` filled in, and no other info:

<img width="1156" alt="screen shot 2016-12-17 at 4 30 48 pm" src="https://cloud.githubusercontent.com/assets/2640861/21289892/860f536c-c476-11e6-80db-e963351fdf17.png">

Then if I do a GET for that applicant, it grabs the record from the API, but only the `id` is filled in.

<img width="394" alt="screen shot 2016-12-17 at 4 30 40 pm" src="https://cloud.githubusercontent.com/assets/2640861/21289893/a6d6c31e-c476-11e6-8eda-a23a2e621f59.png">

<img width="1271" alt="screen shot 2016-12-17 at 4 31 02 pm" src="https://cloud.githubusercontent.com/assets/2640861/21289900/b910ec6c-c476-11e6-9960-5534db885dd6.png">

The API needs to correctly save the applicant model that is sent to it. Then the GET should return all the values filled in. Once the API works correctly, this issue should be fixed. It seems the API only generates an `id` for the applicant, but it should associate the `id` with the applicant and persist the record with `id` and all other fields.

**Comment by ericmaicon** [comment]
@rwwagner90 , solved.

Also, after answer your last question (about mortgages and applicants), I was reviewing the API and we may have an endpoint name problem here. 
We have 3 models in the API: mortgage, applicant and person. Applicant is the relationship between mortgage and person.

This specific endpoint that we are talking about saves a PERSON, even we called applicant. See the name problem?!. Something that I left because of the legacy smartapp code.

We can keep, or we can change to keep consistency. Let's talk about change it (or not) later..just check if worked please.

**Comment by RobbieTheWagner** [comment]
@ericmaicon it works! 🎉 

Since it works now, should we just leave it? I'm definitely open to discussing changes if you would like.
