### ISSUE TITLE
A Custom address component raise an exception after fill the field

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#6]
**Explanation:** In the very first page, fill every field and click on "COMPLETE FULL APPLICATION". It will redirect you to the `applicant` route.
http://smartapp.axiomdev.ca/
Try to add the address, it works.
Try to add a previous address, you may see an exception in the console. Something related to the bind I think.

![captura de tela 2016-12-14 as 17 02 42](https://cloud.githubusercontent.com/assets/1010637/21196558/2cd7530c-c21f-11e6-8ea5-8d012fe9a729.png)

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A Custom address component raise an exception after fill the field](https://trello.com/c/ECCBpfBL/6-a-custom-address-component-raise-an-exception-after-fill-the-field)
