### ISSUE TITLE
"Total employment history: NaN years" Fix the NaN years label.

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#7]
**Explanation:** In the very first page, fill every field and click on "COMPLETE FULL APPLICATION". It will redirect you to the applicant route.
http://smartapp.axiomdev.ca/
Add a previous employment.

**Error:** You may see the following message: ` Total employment history: NaN years`
The logic is here: 
https://github.com/axiommike/smart-app/blob/master/app/components/employment-table.js#L10
I might missed something while I was reviewing/changing the logic.
**Expected:** Return the amount of tenure_years of all employments

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Total employment history: NaN years" Fix the NaN years label.](https://trello.com/c/zcYsXV7Z/7-total-employment-history-nan-years-fix-the-nan-years-label)

**Comment by RobbieTheWagner** [comment]
@ericmaicon I noticed when fixing the NaN issue that currentEmployment is not factored in to the number of years because it is not in the `employments` array. Do we want to factor it in as well or is the total just supposed to be for previous employments, not current?
