### ISSUE TITLE
"Remove" button on previous employment is not working.

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#8]
**Explanation:** In the very first page, fill every field and click on "COMPLETE FULL APPLICATION". It will redirect you to the applicant route.
http://smartapp.axiomdev.ca/
Add a previous employment.

**Error:** Click on "remove employment". It will not remove the employment.

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Remove" button on previous employment is not working](https://trello.com/c/TKhddFe7/8-remove-button-on-previous-employment-is-not-working)
