### ISSUE TITLE
"Remove income source" is not working.

### ISSUE THREAD

**Issue by ericmaicon** [axiommike/smart-app#9]
**Explanation:** In the very first page, fill every field and click on "COMPLETE FULL APPLICATION". It will redirect you to the applicant route.
http://smartapp.axiomdev.ca/
Add a extra income

**Error:** Click on "remove income". It will not remove the extra income.

**Comment by RobbieTheWagner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Remove income source" is not working](https://trello.com/c/uT4MzOnd/9-remove-income-source-is-not-working)
